steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/erudite-wind-274600/kaizaan-100930806:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/erudite-wind-274600/kaizaan-100930806:$COMMIT_SHA']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
